import type { Metadata } from "next";
import "../styles/globals.scss";
import { Hedvig_Letters_Sans, Hedvig_Letters_Serif } from "next/font/google";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

const hedvigSerif = Hedvig_Letters_Serif({
  subsets: ["latin"],
})

const hedvigSans = Hedvig_Letters_Sans({
  weight: '400',
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${hedvigSerif.className} ${hedvigSans.className} body`}>
      <Header/>
      {children}
      <Footer/>
      </body>
    </html>
  );
}
